spring.application.name=ewm-service
server.port=8080

# DataSource Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6542/ewm
spring.datasource.username=ewm
spring.datasource.password=ewm

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Stats Client Configuration
stats-server.url=http://stats-server:9090

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Logging
logging.level.ru.practicum=DEBUG